packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.83.0
  "@trpc/client": ^11.4.0
  "@trpc/server": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  eslint: ^9.28.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.15
  typescript: ^5.9.0-beta
  zod: ^3.25.49

catalogs:
  react19:
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
    react: 19.1.0
    react-dom: 19.1.0

onlyBuiltDependencies:
  - esbuild
